baseURL = "https://joelclarke.co.uk"
disablePathToLower = true
languageCode = "en-uk"
title = "Joel Clarke"
enableEmoji = true
theme = "gokarna"

[menu]
  # [[menu.main]]
  #   identifier = "blog"
  #   name = "Blog"
  #   url = "posts/"
  #   weight = 1
  
  [[menu.main]]
    identifier = "gallery"
    name = "Gallery"
    weight = 2

  [[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "new_cv.pdf"
    weight = 3

[params]
  avatarURL = "avatar.jpeg"
  avatarSize = "size-l"
  description = "Computer Scientist. Amateur Artist."

  socialIcons = [
    {name = "email", url = "mailto:joel.clarke273@gmail.com"},
    {name = "github", url = "https://github.com/DarthEmpty"},
    {name = "linkedin", url = "https://www.linkedin.com/in/joel-clarke-7baa16128/"},
  ]